name: run-tests
on: push
jobs:
  tests:
   runs-on: ubuntu-latest

   steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
    - run: npm install
    - run: make lint
    - run: make test